name: Deploy API Hoper

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      HF_API_KEY: ${{ secrets.HF_API_KEY }}
      AI21_API_KEY: ${{ secrets.AI21_API_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      CARGO_HOME: ${{ github.workspace }}/.cargo  # <-- adicionada variável de cache Rust

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Prepare Rust cache
        run: mkdir -p $CARGO_HOME

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --prefer-binary -r requirements.txt  # <-- forçar wheels

      - name: Run tests (exemplo)
        run: |
          echo "Rodando testes..."
          # pytest tests/
