# Extra index para PyTorch CPU
--extra-index-url https://download.pytorch.org/whl/cpu

# Dependências principais
fastapi==0.110.1
uvicorn[standard]==0.29.0
pydantic==2.7.1
openai==1.30.3
ai21
transformers==4.30.2       # versão antiga sem tokenizers obrigatório
accelerate==0.30.1
requests==2.31.0
aiohttp==3.12.0
httpx==0.27.0
gtts==2.5.1
python-multipart==0.0.9
torch==2.5.0               # puxará CPU do index acima
python-dotenv==1.0.1
loguru==0.7.2

# Extras (opcionais)
apscheduler==3.10.4
sqlalchemy==2.0.30
prometheus-fastapi-instrumentator==6.1.0
