services:
  - type: web
    name: hoper-api
    env: python
    plan: free

    # Comando de build
    buildCommand: ./build.sh

    # Comando para iniciar a API
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    # Variáveis de ambiente
    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: HF_API_KEY
        value: ${HF_API_KEY}
      - key: AI21_API_KEY
        value: ${AI21_API_KEY}
      - key: OPENROUTER_API_KEY
        value: ${OPENROUTER_API_KEY}
      - key: GOOGLE_API_KEY
        value: ${GOOGLE_API_KEY}
      - key: CARGO_HOME
        value: /tmp/cargo
      - key: RUSTUP_HOME
        value: /tmp/rustup
