name: Deploy API Hoper

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      HF_API_KEY: ${{ secrets.HF_API_KEY }}
      AI21_API_KEY: ${{ secrets.AI21_API_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --prefer-binary -r requirements.txt

      - name: Run tests (opcional)
        run: |
          echo "Rodando testes..."
          # pytest tests/

      - name: Start API (para teste local)
        run: uvicorn main:app --host 0.0.0.0 --port 8000
