services:
  - type: web
    name: hoper-api
    env: python
    plan: free
    pythonVersion: 3.12.6   # 👈 força Python 3.12

    buildCommand: ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: HF_API_KEY
        value: ${HF_API_KEY}
      - key: AI21_API_KEY
        value: ${AI21_API_KEY}
      - key: OPENROUTER_API_KEY
        value: ${OPENROUTER_API_KEY}
      - key: GOOGLE_API_KEY
        value: ${GOOGLE_API_KEY}
 key: FIREBASE_CRED_JSON
        value: ${FIREBASE_CRED_JSON}

