services:
  - type: web
    name: hoper-api
    env: python
    plan: free

    # Comando de build
    buildCommand: |
      # Forçar cache local do Rust (precaução, maturin nem será chamado)
      export CARGO_HOME=/opt/render/.cargo
      mkdir -p $CARGO_HOME

      # Atualizar pip e ferramentas essenciais
      python -m pip install --upgrade pip setuptools wheel

      # Instalar dependências usando wheels sempre que possível
      pip install --prefer-binary -r requirements.txt

    # Comando para iniciar a API
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    # Variáveis de ambiente (secrets mantidos intactos)
    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: HF_API_KEY
        value: ${HF_API_KEY}
      - key: AI21_API_KEY
        value: ${AI21_API_KEY}
      - key: OPENROUTER_API_KEY
        value: ${OPENROUTER_API_KEY}
      - key: GOOGLE_API_KEY
        value: ${GOOGLE_API_KEY}
      - key: CARGO_HOME
        value: /opt/render/.cargo
